### ISSUE TITLE
Cannot enable the addon

### ISSUE THREAD

**Issue by dotryen** [example-sk/audvis#13]
Enabling the package immediately throws an error.
Stating that it cannot import `aud` for some reason?

Trace
```
Traceback (most recent call last):
  File "/usr/share/blender/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/__init__.py", line 20, in <module>
    from . import ui
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/ui/__init__.py", line 6, in <module>
    from . import (
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/ui/props/__init__.py", line 1, in <module>
    from . import (
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/ui/props/spectrogram.py", line 3, in <module>
    from .midi import AudvisMidiGeneratorsProperties
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/ui/props/midi.py", line 3, in <module>
    from .. import midi as ui_midi
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/ui/midi/__init__.py", line 1, in <module>
    from . import realtime, file
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/ui/midi/realtime.py", line 11, in <module>
    from ...analyzer.midi_realtime import _MidiNoteMessage
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/analyzer/midi_realtime/__init__.py", line 4, in <module>
    from ..analyzer import Analyzer
  File "/home/ryen/.config/blender/4.1/scripts/addons/audvis/analyzer/analyzer.py", line 3, in <module>
    import aud
ModuleNotFoundError: No module named 'aud'
```

OS: Arch Linux

**Comment by example-sk** [comment]
Hi. Please, how did you install / unzip / build Blender? By my understanding, module `aud` is part of Blender. If this module is missing, you have probably some minimal build or something...

**Comment by dotryen** [comment]
I installed Blender via the official package manager `pacman`. It is also the only Blender package in the official list. I believe I have all optional packages as well. I just imported some music and it also does play it back.

I used this test script and it throws the same error as well.
```
import aud

print("success")
```
I'm currently trying to find out why it is missing.

**Comment by dotryen** [comment]
I found the issue. Turns out Audaspace (`aud`) is an external library as the Blender documentation states that it is a "Standalone Module." I had to install `audaspace` from the package manager as well. Audaspace being an optional dependency is stated nowhere aside from that hint.

Anyway I can enable the addon now.
Thank you for wanting to help.

**Comment by example-sk** [comment]
Interesting... I thought Blender packages all python dependencies to avoid problems like this. And that it uses its own aud build. It looks like I was wrong about it.

**Comment by dotryen** [comment]
I think it might depend on which Linux distribution you're using. Or like you stated, how you install it.
